export const encounterFlavor = {
  normal: [
    'ENTERING CHANNEL',
    'SIGNAL PATH OPEN',
    'QUIET CURRENT FOUND',
    'NAVIGATION STREAM ALIGNED',
    'FORWARD RELAY AVAILABLE',
    'STABLE ROUTE DETECTED',
    'CHANNEL MEMORY CLEAR',
    'BLUE CARRIER LOCKED'
  ],
  fork: [
    'BRANCH DENSITY RISING',
    'FORK LATTICE DETECTED',
    'ROUTE CHOICES APPROACHING',
    'SPLIT CURRENT AHEAD',
    'DIVERGENT SIGNALS FORMING',
    'BRANCH PRESSURE INCREASING',
    'ROUTE GEOMETRY UNFOLDING',
    'DECISION STREAM OPEN'
  ],
  pressure: [
    'STATIC DENSITY RISING',
    'ARCHIVE PRESSURE INCREASING',
    'HOSTILE CARRIER NEAR',
    'SIGNAL DEBT ACCUMULATING',
    'BLOOM FIELD INTENSIFYING',
    'RED NOISE APPROACHING',
    'ERROR WAKE EXPANDING',
    'PRESSURE CHANNEL ENGAGED'
  ],
  recovery: [
    'RECOVERY SIGNAL DETECTED',
    'REPAIR CURRENT AVAILABLE',
    'STABILITY WINDOW OPEN',
    'INTEGRITY ROUTE FORMING',
    'CALM RELAY RESPONDING',
    'CLEAN SIGNAL RETURNING',
    'MAINTENANCE STREAM OPEN',
    'ANCHOR POINT AVAILABLE'
  ],
  multiStream: [
    'PARALLEL STREAMS CONVERGING',
    'PRIORITY SPLIT FORMING',
    'SECONDARY SIGNAL ACTIVE',
    'COMPETING STREAMS DETECTED',
    'LANE PRESSURE DIVIDING',
    'MULTI-CHANNEL EVENT',
    'FOCUS WINDOW NARROWING',
    'CONCURRENT ROUTES ONLINE'
  ],
  finalePrep: [
    'SIGNAL DRIFT DETECTED',
    'FINAL STREAM ALIGNING',
    'CORE CURRENT VISIBLE',
    'CONVERGENCE FIELD RISING',
    'LAST RELAY UNLOCKING',
    'ARCHIVE LIGHT COLLAPSING',
    'CENTRAL CHANNEL NEAR',
    'FINAL APPROACH STABILIZING'
  ],
  finale: [
    'SIGNAL CONVERGENCE IMMINENT',
    'FINAL STREAM APPROACHING',
    'CORE SIGNAL OPEN',
    'CONVERGENCE LOCK ENGAGED',
    'LAST TRANSMISSION ACTIVE',
    'PRIMARY STREAM COLLAPSING',
    'FINAL CHANNEL IGNITION',
    'STABILIZATION WINDOW CLOSING'
  ]
};
