export const routePhrases = [
  { text: 'follow the quiet channel', routeType: 'safe', difficulty: 1, tags: ['navigation', 'stable'] },
  { text: 'hold the steady current', routeType: 'safe', difficulty: 1, tags: ['navigation', 'stable'] },
  { text: 'trace the calm signal', routeType: 'safe', difficulty: 1, tags: ['signal', 'stable'] },
  { text: 'enter the low tide path', routeType: 'safe', difficulty: 1, tags: ['navigation', 'low-risk'] },
  { text: 'keep to the green line', routeType: 'safe', difficulty: 1, tags: ['navigation', 'stable'] },
  { text: 'cross the silent lane', routeType: 'safe', difficulty: 1, tags: ['navigation', 'quiet'] },
  { text: 'drift under clear static', routeType: 'safe', difficulty: 2, tags: ['signal', 'stable'] },
  { text: 'align with stable pulse', routeType: 'safe', difficulty: 2, tags: ['signal', 'stable'] },

  { text: 'chase the bright relay', routeType: 'reward', difficulty: 2, tags: ['reward', 'signal'] },
  { text: 'open the signal cache', routeType: 'reward', difficulty: 2, tags: ['reward', 'cache'] },
  { text: 'ride the bonus carrier', routeType: 'reward', difficulty: 2, tags: ['reward', 'navigation'] },
  { text: 'capture the gold packet', routeType: 'reward', difficulty: 2, tags: ['reward', 'packet'] },
  { text: 'thread the prize vector', routeType: 'reward', difficulty: 3, tags: ['reward', 'vector'] },
  { text: 'claim the overbright node', routeType: 'reward', difficulty: 3, tags: ['reward', 'node'] },
  { text: 'decode the rare carrier', routeType: 'reward', difficulty: 3, tags: ['reward', 'signal'] },
  { text: 'pull from the bright archive', routeType: 'reward', difficulty: 3, tags: ['reward', 'archive'] },

  { text: 'repair the left conduit', routeType: 'repair', difficulty: 2, tags: ['repair', 'conduit'] },
  { text: 'restore the main gasket', routeType: 'repair', difficulty: 2, tags: ['repair', 'machine'] },
  { text: 'seal the cracked mirror', routeType: 'repair', difficulty: 2, tags: ['repair', 'mirror'] },
  { text: 'reset the coolant phrase', routeType: 'repair', difficulty: 2, tags: ['repair', 'coolant'] },
  { text: 'patch the archive gate', routeType: 'repair', difficulty: 2, tags: ['repair', 'archive'] },
  { text: 'mend the primary channel', routeType: 'repair', difficulty: 3, tags: ['repair', 'channel'] },
  { text: 'clean the damaged carrier', routeType: 'repair', difficulty: 3, tags: ['repair', 'signal'] },
  { text: 'restore the anchor tone', routeType: 'repair', difficulty: 3, tags: ['repair', 'anchor'] },

  { text: 'read the buried message', routeType: 'archive', difficulty: 2, tags: ['archive', 'lore'] },
  { text: 'recover old navigation', routeType: 'archive', difficulty: 2, tags: ['archive', 'navigation'] },
  { text: 'scan the silent ledger', routeType: 'archive', difficulty: 2, tags: ['archive', 'ledger'] },
  { text: 'unlock memory protocol', routeType: 'archive', difficulty: 3, tags: ['archive', 'memory'] },
  { text: 'translate the amber log', routeType: 'archive', difficulty: 3, tags: ['archive', 'translation'] },
  { text: 'open the forgotten index', routeType: 'archive', difficulty: 3, tags: ['archive', 'index'] },
  { text: 'parse the sealed dispatch', routeType: 'archive', difficulty: 3, tags: ['archive', 'dispatch'] },
  { text: 'retrieve the lost manifest', routeType: 'archive', difficulty: 3, tags: ['archive', 'manifest'] },

  { text: 'pierce the red static', routeType: 'corruption', difficulty: 3, tags: ['corruption', 'static'] },
  { text: 'cross the hostile carrier', routeType: 'corruption', difficulty: 3, tags: ['corruption', 'carrier'] },
  { text: 'drink from the error stream', routeType: 'corruption', difficulty: 3, tags: ['corruption', 'risk'] },
  { text: 'decode the broken omen', routeType: 'corruption', difficulty: 3, tags: ['corruption', 'omen'] },
  { text: 'enter the fracture pulse', routeType: 'corruption', difficulty: 4, tags: ['corruption', 'fracture'] },
  { text: 'follow the crimson packet', routeType: 'corruption', difficulty: 4, tags: ['corruption', 'packet'] },
  { text: 'open the unstable lock', routeType: 'corruption', difficulty: 4, tags: ['corruption', 'lock'] },
  { text: 'cut through thorned signal', routeType: 'corruption', difficulty: 4, tags: ['corruption', 'signal'] }
];
