CREATE DATABASE IF NOT EXISTS game_scores;

USE game_scores;

CREATE TABLE IF NOT EXISTS scores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(12) NOT NULL,
  score INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX score_idx (score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
