export const DROID_BEHAVIOR_PROFILES = {
  GUARD: 'guard',
  SINGLE_ROOM_PATROL: 'single-room-patrol',
  MULTI_ROOM_PATROL: 'multi-room-patrol',
  LEVEL_PATROL: 'level-patrol',
  WANDER: 'wander'
};

const MODEL_PROFILE_OVERRIDES = new Map([
  [120, DROID_BEHAVIOR_PROFILES.WANDER],
  [145, DROID_BEHAVIOR_PROFILES.SINGLE_ROOM_PATROL],
  [175, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [210, DROID_BEHAVIOR_PROFILES.SINGLE_ROOM_PATROL],
  [230, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [275, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [302, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [330, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [375, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [410, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [450, DROID_BEHAVIOR_PROFILES.GUARD],
  [475, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [520, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [575, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [590, DROID_BEHAVIOR_PROFILES.GUARD],
  [620, DROID_BEHAVIOR_PROFILES.SINGLE_ROOM_PATROL],
  [660, DROID_BEHAVIOR_PROFILES.GUARD],
  [690, DROID_BEHAVIOR_PROFILES.GUARD],
  [735, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [760, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [790, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [840, DROID_BEHAVIOR_PROFILES.GUARD],
  [880, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [895, DROID_BEHAVIOR_PROFILES.LEVEL_PATROL],
  [910, DROID_BEHAVIOR_PROFILES.GUARD],
  [950, DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL],
  [999, DROID_BEHAVIOR_PROFILES.GUARD]
]);

export function getBehaviorProfileForTemplate(template) {
  if (!template) {
    return DROID_BEHAVIOR_PROFILES.WANDER;
  }
  if (MODEL_PROFILE_OVERRIDES.has(template.rank)) {
    return MODEL_PROFILE_OVERRIDES.get(template.rank);
  }

  const series = Math.floor(template.rank / 100);
  if (series <= 1) return DROID_BEHAVIOR_PROFILES.WANDER;
  if (series === 2) return DROID_BEHAVIOR_PROFILES.SINGLE_ROOM_PATROL;
  if (series === 3) return DROID_BEHAVIOR_PROFILES.LEVEL_PATROL;
  if (series === 4) return DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL;
  if (series === 5) return DROID_BEHAVIOR_PROFILES.MULTI_ROOM_PATROL;
  if (series === 6) return DROID_BEHAVIOR_PROFILES.GUARD;
  if (series === 7) return DROID_BEHAVIOR_PROFILES.LEVEL_PATROL;
  if (series >= 8) return DROID_BEHAVIOR_PROFILES.LEVEL_PATROL;
  return DROID_BEHAVIOR_PROFILES.WANDER;
}

export function canTemplateUseRepairPads(template) {
  if (!template) {
    return false;
  }
  if (template.rank === 145) {
    return true;
  }
  const series = Math.floor(template.rank / 100);
  return series >= 4;
}

export function canAggroLeaveHome(profile, template) {
  if (template?.weaponType === 'none') {
    return true;
  }
  return profile !== DROID_BEHAVIOR_PROFILES.GUARD &&
    profile !== DROID_BEHAVIOR_PROFILES.SINGLE_ROOM_PATROL;
}
