import PageMeta from "../components/PageMeta";
import { siteContent } from "../content/siteContent";

const projects = [
  ["⌘", "LODEX", "A local-first AI software engineering assistant for safely planning, understanding, and modifying codebases while keeping everything under the user's control."],
  ["◫", "Cinelingus", "An experimental filmmaking tool that remixes dialogue, performances, and timing into entirely new cinematic experiences."],
  ["↗", "Billionaire Simulator", "A large-scale economic and business simulation of wealth, investment, companies, and emergent storytelling."],
  ["✦", "Enchanted Castle Rebooted", "A modern reimagining of a classic text adventure with parser-driven exploration and rich procedural storytelling."],
  ["◎", "Angle Wars", "A loving successor to Scorched Earth: ridiculous artillery, chaotic physics, extravagant weapons, and just enough strategy."],
] as const;
const opportunities = ["AI-assisted software engineering", "Python development", "Procedural generation", "Creative technology", "Data engineering and analytics", "Game tools and simulation", "Experimental media"];
function GitHubIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M12 .7A11.5 11.5 0 0 0 8.4 23c.6.1.8-.3.8-.6v-2.2c-3.4.7-4.1-1.4-4.1-1.4-.6-1.4-1.4-1.8-1.4-1.8-1.1-.8.1-.8.1-.8 1.3.1 1.9 1.3 1.9 1.3 1.1 1.9 2.9 1.4 3.6 1.1.1-.8.4-1.4.8-1.7-2.7-.3-5.5-1.3-5.5-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.6.1-3.1 0 0 1-.3 3.2 1.2a11 11 0 0 1 5.8 0c2.2-1.5 3.2-1.2 3.2-1.2.6 1.5.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.8 5.4-5.5 5.7.4.4.8 1.1.8 2.2v3.3c0 .4.2.7.8.6A11.5 11.5 0 0 0 12 .7Z" /></svg>; }
export default function ContactPage() {
  return <main className="site-page contact-page">
    <PageMeta title="Meet the Studio | Wingtip Studio" description="Meet Wingtip Studio and Jared Menard: independent work spanning software, games, music, AI, and procedural creativity." />
    <header className="page-intro contact-intro"><p className="eyebrow">Studio Notes</p><h1>Contact</h1><p>Meet the artist-engineer behind the games, music, tools, and strange machines.</p></header>
    <section className="contact-about" aria-labelledby="about-title"><div><p className="contact-label">The Workshop</p><h2 id="about-title">About Wingtip Studio</h2><p className="contact-lede">Wingtip Studio is where I build the projects I wish already existed.</p><p>My interests sit somewhere between software engineering, procedural generation, game design, and music composition. Most of the work here starts as a simple question—“What if this were possible?”—and turns into months of designing, building, testing, and refining until there's something real.</p><p>Some projects become games. Others become tools, albums, AI experiments, or strange interactive ideas that don't fit neatly into any category. They're united by a love of systems, craftsmanship, and discovering unexpected results.</p><p>This site is both a portfolio and a workshop. Everything here is built independently, one project at a time.</p></div><figure><img src={siteContent.home.heroArtwork.src} alt={siteContent.home.heroArtwork.alt} /><figcaption>{siteContent.home.heroArtwork.title}</figcaption></figure></section>
    <div className="contact-duo"><section className="contact-philosophy"><p className="contact-label">Creative Systems</p><h2>The Philosophy</h2><p>I'm fascinated by software that creates rather than merely automates.</p><p>Whether it's simulating entire worlds, generating stories and music, remixing films in impossible ways, or building local AI tools that help create new work, the goal is always the same: make computers a little more imaginative.</p><p>I believe the most interesting projects live where disciplines overlap. Games borrow from music. Music borrows from mathematics. Artificial intelligence becomes another creative instrument. Those intersections are where Wingtip Studio spends most of its time.</p><p>If something here makes you smile, makes you curious, or inspires you to build something of your own, then the project has already succeeded.</p><blockquote>“I'm interested in building systems that surprise even their creator.”</blockquote></section><section className="contact-github"><p className="contact-label">Public Workshop</p><h2>Open Source &amp; Development</h2><p>Many of my software projects are developed in the open. You'll find game engines, procedural generation experiments, AI tools, utilities, prototypes, and the occasional wonderfully strange idea.</p><p>If you're interested in how something works, GitHub is usually the best place to start.</p><a href="https://github.com/primalfunk" target="_blank" rel="noreferrer"><GitHubIcon /><span><small>Explore the source</small>github.com/primalfunk</span><b>↗</b></a></section></div>
    <section className="contact-building"><header><p className="contact-label">Works in Progress</p><h2>Currently Building</h2><p>Most of my time is spent developing a handful of long-term projects. They're ambitious, occasionally strange, and always evolving.</p></header><div className="contact-projects">{projects.map(([icon,title,description],i)=><article key={title}><span className="number">0{i+1}</span><span className="icon">{icon}</span><div>{title === "Angle Wars" && <small>Bureau of Bad Ideas</small>}<h3>{title}</h3><p>{description}</p></div></article>)}</div><p className="note">Many of these projects are documented publicly as they evolve. Some are experiments. Others may eventually become complete commercial releases.</p></section>
    <section className="contact-opportunities"><div><p className="contact-label">Collaborations &amp; Employment</p><h2>Opportunities</h2><p className="contact-lede">I'm always interested in interesting conversations.</p><p>Whether you're looking for someone to help build software, collaborate on creative technology, develop AI-powered tools, compose music, or simply explore an unusual idea, I'd be happy to hear from you.</p><p>If you think we'd enjoy building something together, let's talk.</p></div><ul>{opportunities.map(x=><li key={x}>{x}</li>)}</ul></section>
    <section className="contact-final"><p className="contact-label">Direct Line</p><h2>Contact</h2><p>Email remains the best way to reach me.</p><a href={`mailto:${siteContent.contact.email}`}><span>✉</span>{siteContent.contact.email}</a><p className="closing">Tell me what you're imagining.</p></section>
  </main>;
}
