import type { DrillScenario } from "../core/types";

export const DRILL_SCENARIOS: DrillScenario[] = [
  {
    id: "pf_btn_open_01",
    spotKey: "preflop_btn_open_hu",
    title: "BTN Open: Premium Pair",
    teachingNote: "Anchor the wide-button opening concept with a clear value open.",
    focusArea: "opening range",
    effectiveStackBb: 50,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "button",
    villainPosition: "big_blind",
    heroHole: ["As", "Ah"],
    board: [],
    pot: 0,
    heroCommitted: 10,
    botCommitted: 20,
    heroStack: 990,
    botStack: 980,
    currentBet: 20,
    minRaiseAmount: 20,
    street: "preflop",
    toAct: "hero",
    actionHistory: [],
    legalActions: ["fold", "call", "raise"]
  },
  {
    id: "pf_btn_open_02",
    spotKey: "preflop_btn_open_hu",
    title: "BTN Open: Suited Wheel Ace",
    teachingNote: "Still an open despite lower raw pair strength.",
    focusArea: "opening range",
    effectiveStackBb: 45,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "button",
    villainPosition: "big_blind",
    heroHole: ["Ac", "5c"],
    board: [],
    pot: 0,
    heroCommitted: 10,
    botCommitted: 20,
    heroStack: 890,
    botStack: 880,
    currentBet: 20,
    minRaiseAmount: 20,
    street: "preflop",
    toAct: "hero",
    actionHistory: [],
    legalActions: ["fold", "call", "raise"]
  },
  {
    id: "pf_bb_defend_01",
    spotKey: "preflop_bb_defend_hu",
    title: "BB Defend: Broadways vs Min-Open",
    teachingNote: "Classic defend-or-3-bet mix spot.",
    focusArea: "bb defense",
    effectiveStackBb: 50,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "big_blind",
    villainPosition: "button",
    heroHole: ["Kd", "Qs"],
    board: [],
    pot: 0,
    heroCommitted: 20,
    botCommitted: 50,
    heroStack: 980,
    botStack: 950,
    currentBet: 50,
    minRaiseAmount: 30,
    street: "preflop",
    toAct: "hero",
    actionHistory: [{ street: "preflop", actor: "bot", action: "raise", amount: 50 }],
    legalActions: ["fold", "call", "raise"]
  },
  {
    id: "flop_ip_cbet_01",
    spotKey: "flop_srp_ip_cbet",
    title: "Flop C-Bet Dry Ace-High Board",
    teachingNote: "Range advantage and initiative make this a natural c-bet candidate.",
    focusArea: "flop c-bet",
    effectiveStackBb: 48,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "button",
    villainPosition: "big_blind",
    heroHole: ["Kd", "Qc"],
    board: ["As", "7d", "2c"],
    pot: 100,
    heroCommitted: 0,
    botCommitted: 0,
    heroStack: 910,
    botStack: 890,
    currentBet: 0,
    minRaiseAmount: 20,
    street: "flop",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "hero", action: "raise", amount: 50 },
      { street: "preflop", actor: "bot", action: "call", amount: 30 },
      { street: "flop", actor: "bot", action: "check" }
    ],
    legalActions: ["check", "bet"]
  },
  {
    id: "flop_ip_cbet_02",
    spotKey: "flop_srp_ip_cbet",
    title: "Flop C-Bet Wet Broadway Board",
    teachingNote: "Texture is dynamic; size and frequency should tighten.",
    focusArea: "board texture",
    effectiveStackBb: 47,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "button",
    villainPosition: "big_blind",
    heroHole: ["Ah", "Td"],
    board: ["Jh", "9h", "7c"],
    pot: 100,
    heroCommitted: 0,
    botCommitted: 0,
    heroStack: 890,
    botStack: 890,
    currentBet: 0,
    minRaiseAmount: 20,
    street: "flop",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "hero", action: "raise", amount: 50 },
      { street: "preflop", actor: "bot", action: "call", amount: 30 },
      { street: "flop", actor: "bot", action: "check" }
    ],
    legalActions: ["check", "bet"]
  },
  {
    id: "flop_oop_defend_01",
    spotKey: "flop_srp_oop_defend_vs_cbet",
    title: "Flop OOP Defend on Dry Board",
    teachingNote: "Hero defended preflop and now faces a routine c-bet.",
    focusArea: "flop defense",
    effectiveStackBb: 46,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "big_blind",
    villainPosition: "button",
    heroHole: ["Qs", "7s"],
    board: ["Kc", "7d", "2h"],
    pot: 100,
    heroCommitted: 0,
    botCommitted: 35,
    heroStack: 885,
    botStack: 865,
    currentBet: 35,
    minRaiseAmount: 35,
    street: "flop",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "bot", action: "raise", amount: 50 },
      { street: "preflop", actor: "hero", action: "call", amount: 30 },
      { street: "flop", actor: "hero", action: "check" },
      { street: "flop", actor: "bot", action: "bet", amount: 35 }
    ],
    legalActions: ["fold", "call", "raise"]
  },
  {
    id: "flop_oop_defend_02",
    spotKey: "flop_srp_oop_defend_vs_cbet",
    title: "Flop OOP Defend on Wet Board",
    teachingNote: "Connected two-tone boards demand more caution versus c-bets.",
    focusArea: "board texture",
    effectiveStackBb: 45,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "big_blind",
    villainPosition: "button",
    heroHole: ["9h", "8d"],
    board: ["Th", "7h", "6c"],
    pot: 100,
    heroCommitted: 0,
    botCommitted: 50,
    heroStack: 860,
    botStack: 850,
    currentBet: 50,
    minRaiseAmount: 50,
    street: "flop",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "bot", action: "raise", amount: 50 },
      { street: "preflop", actor: "hero", action: "call", amount: 30 },
      { street: "flop", actor: "hero", action: "check" },
      { street: "flop", actor: "bot", action: "bet", amount: 50 }
    ],
    legalActions: ["fold", "call", "raise"]
  },
  {
    id: "turn_barrel_01",
    spotKey: "turn_barrel_after_flop_call",
    title: "Turn Barrel on Blank",
    teachingNote: "After a flop c-bet gets called, blank turns still reward continued pressure.",
    focusArea: "turn barreling",
    effectiveStackBb: 43,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "button",
    villainPosition: "big_blind",
    heroHole: ["Ad", "Kc"],
    board: ["Qs", "7d", "2c", "4h"],
    pot: 170,
    heroCommitted: 0,
    botCommitted: 0,
    heroStack: 810,
    botStack: 810,
    currentBet: 0,
    minRaiseAmount: 20,
    street: "turn",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "hero", action: "raise", amount: 50 },
      { street: "preflop", actor: "bot", action: "call", amount: 30 },
      { street: "flop", actor: "bot", action: "check" },
      { street: "flop", actor: "hero", action: "bet", amount: 35 },
      { street: "flop", actor: "bot", action: "call", amount: 35 },
      { street: "turn", actor: "bot", action: "check" }
    ],
    legalActions: ["check", "bet"]
  },
  {
    id: "turn_barrel_02",
    spotKey: "turn_checkback_after_cbet",
    title: "Turn Barrel with Equity",
    teachingNote: "Strong draws can continue betting for fold equity plus realization.",
    focusArea: "turn barreling",
    effectiveStackBb: 48,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "button",
    villainPosition: "big_blind",
    heroHole: ["Ah", "Jh"],
    board: ["Kh", "8h", "3c", "2s"],
    pot: 200,
    heroCommitted: 0,
    botCommitted: 0,
    heroStack: 860,
    botStack: 860,
    currentBet: 0,
    minRaiseAmount: 20,
    street: "turn",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "hero", action: "raise", amount: 50 },
      { street: "preflop", actor: "bot", action: "call", amount: 30 },
      { street: "flop", actor: "bot", action: "check" },
      { street: "flop", actor: "hero", action: "bet", amount: 50 },
      { street: "flop", actor: "bot", action: "call", amount: 50 },
      { street: "turn", actor: "bot", action: "check" }
    ],
    legalActions: ["check", "bet"]
  },
  {
    id: "river_bluffcatch_01",
    spotKey: "river_bluffcatch_vs_bet",
    title: "River Bluffcatch vs Medium Bet",
    teachingNote: "The price invites more bluff-catching than an overbet would.",
    focusArea: "river bluff-catching",
    effectiveStackBb: 38,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "big_blind",
    villainPosition: "button",
    heroHole: ["Qh", "9d"],
    board: ["Qs", "7c", "3d", "2h", "Jc"],
    pot: 180,
    heroCommitted: 0,
    botCommitted: 90,
    heroStack: 670,
    botStack: 650,
    currentBet: 90,
    minRaiseAmount: 90,
    street: "river",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "bot", action: "raise", amount: 50 },
      { street: "preflop", actor: "hero", action: "call", amount: 30 },
      { street: "flop", actor: "hero", action: "check" },
      { street: "flop", actor: "bot", action: "check" },
      { street: "turn", actor: "hero", action: "check" },
      { street: "turn", actor: "bot", action: "check" },
      { street: "river", actor: "hero", action: "check" },
      { street: "river", actor: "bot", action: "bet", amount: 90 }
    ],
    legalActions: ["fold", "call", "raise"]
  },
  {
    id: "river_bluffcatch_02",
    spotKey: "river_bluffcatch_vs_bet",
    title: "River Bluffcatch vs Polar Bet",
    teachingNote: "Paired rivers often narrow villain into value-or-bluff buckets.",
    focusArea: "river bluff-catching",
    effectiveStackBb: 44,
    blinds: { sb: 10, bb: 20 },
    heroPosition: "big_blind",
    villainPosition: "button",
    heroHole: ["Ad", "7h"],
    board: ["Ac", "Tc", "4s", "4d", "2h"],
    pot: 220,
    heroCommitted: 0,
    botCommitted: 190,
    heroStack: 690,
    botStack: 670,
    currentBet: 190,
    minRaiseAmount: 190,
    street: "river",
    toAct: "hero",
    actionHistory: [
      { street: "preflop", actor: "bot", action: "raise", amount: 50 },
      { street: "preflop", actor: "hero", action: "call", amount: 30 },
      { street: "flop", actor: "hero", action: "check" },
      { street: "flop", actor: "bot", action: "check" },
      { street: "turn", actor: "hero", action: "check" },
      { street: "turn", actor: "bot", action: "check" },
      { street: "river", actor: "hero", action: "check" },
      { street: "river", actor: "bot", action: "bet", amount: 190 }
    ],
    legalActions: ["fold", "call", "raise"]
  }
];
