import { createPhraseEntries } from '../schema.js';

export const navigationPhrases = createPhraseEntries('nav', [
  { text: 'follow the quiet channel', difficulty: 1, biome: 'signalArchive' },
  { text: 'hold the stable course', difficulty: 1, biome: 'mirrorConduit' },
  { text: 'enter the signal river', difficulty: 1, biome: 'coreStream' },
  { text: 'trace the blue carrier', difficulty: 1, biome: 'signalArchive' },
  { text: 'cross the open relay', difficulty: 1, biome: 'deadRelay' },
  { text: 'keep the stream centered', difficulty: 1, biome: 'mirrorConduit' },
  { text: 'align the forward path', difficulty: 1, biome: 'coreStream' },
  { text: 'read the route marker', difficulty: 1, biome: 'signalArchive' },
  { text: 'steer by the pale beacon', difficulty: 2, biome: 'deadRelay' },
  { text: 'follow the mapped current', difficulty: 2, biome: 'coreStream' },
  { text: 'route through clear water', difficulty: 2, biome: 'mirrorConduit' },
  { text: 'pass beneath the archive gate', difficulty: 2, biome: 'signalArchive' },
  { text: 'match the stable frequency', difficulty: 2, biome: 'staticBloom' },
  { text: 'thread the narrow signal', difficulty: 2, biome: 'coreStream' },
  { text: 'keep left of static bloom', difficulty: 2, biome: 'staticBloom' },
  { text: 'follow the low green pulse', difficulty: 2, biome: 'deadRelay' },
  { text: 'circle the mirror conduit', difficulty: 2, biome: 'mirrorConduit' },
  { text: 'hold course through drift', difficulty: 2, biome: 'staticBloom' },
  { text: 'decode the lane beacon', difficulty: 2, biome: 'signalArchive' },
  { text: 'enter the calm tributary', difficulty: 2, biome: 'coreStream' },
  { text: 'slide past the dead relay', difficulty: 3, biome: 'deadRelay' },
  { text: 'stabilize the route vector', difficulty: 3, biome: 'coreStream' },
  { text: 'navigate by reflected light', difficulty: 3, biome: 'mirrorConduit' },
  { text: 'follow the archived bearing', difficulty: 3, biome: 'signalArchive' },
  { text: 'correct the lateral drift', difficulty: 3, biome: 'staticBloom' },
  { text: 'chart the folded current', difficulty: 3, biome: 'mirrorConduit' },
  { text: 'open the downstream lock', difficulty: 3, biome: 'deadRelay' },
  { text: 'tune the route harmonics', difficulty: 3, biome: 'coreStream' },
  { text: 'sequence the outer markers', difficulty: 3, biome: 'signalArchive' },
  { text: 'run below the static shelf', difficulty: 3, biome: 'staticBloom' },
  { text: 'resolve the mirror bearing', difficulty: 4, biome: 'mirrorConduit' },
  { text: 'cross-reference the channel', difficulty: 4, biome: 'signalArchive' },
  { text: 'bypass the fractured relay', difficulty: 4, biome: 'deadRelay' },
  { text: 'thread the oscillating lane', difficulty: 4, biome: 'staticBloom' },
  { text: 'synchronize the core vector', difficulty: 4, biome: 'coreStream' },
  { text: 'fold around the echo bend', difficulty: 4, biome: 'mirrorConduit' },
  { text: 'approach the central stream', difficulty: 4, biome: 'coreStream' },
  { text: 'correct course at relay zero', difficulty: 4, biome: 'deadRelay' },
  { text: 'map the archive undercurrent', difficulty: 4, biome: 'signalArchive' },
  { text: 'navigate the bright interference', difficulty: 4, biome: 'staticBloom' }
], {
  routeType: 'safe',
  streamRole: 'primary',
  tags: ['navigation', 'stable'],
  rewardHint: 'progress'
});
